### ISSUE TITLE
Add and configure prettier

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/sprucecss#17]
Latest stylelint does not check formatting.
https://prettier.io/docs/en/configuration
`.prettierrc.yml`

**Comment by szepeviktor** [comment]
stylelint could also have a human-friendly `.stylelintrc.yml`

**Comment by szepeviktor** [comment]
@adamlaki Easy.

`.prettierrc.yml`
```yaml
tabWidth: 2
printWidth: 120
semi: true
singleQuote: true
trailingComma: "es5"
```

```shell
prettier --check preview/assets/scss/ preview/assets/js/ preview/pug/ scss/ test/
# and --write
```
